name: Pipeline

env:
  GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
  HUSKY: 0
  PIPELINE_USER_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  PIPELINE_USER_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  PROD_CLOUDFORMATION_EXECUTION_ROLE: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/choosee-cloudformation
  PROD_PIPELINE_EXECUTION_ROLE: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/choosee-pipeline
  PROD_REGION: ${{ secrets.AWS_REGION }}
  PROD_S3_BUCKET: choosee-ui-source
  PROD_STACK_NAME: choosee-ui
  TEMPLATE_NAME: template.yaml
  TESTING_CLOUDFORMATION_EXECUTION_ROLE: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/choosee-cloudformation-test
  TESTING_PIPELINE_EXECUTION_ROLE: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/choosee-pipeline-test
  TESTING_REGION: ${{ secrets.AWS_REGION }}
  TESTING_S3_BUCKET: choosee-ui-test
  TESTING_STACK_NAME: choosee-ui-test

on: push

permissions:
  contents: write

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v6
      - name: Install Node 24
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
      - name: Install and audit packages
        run: npm ci --legacy-peer-deps && npm audit --audit-level=critical
        env:
          NODE_ENV: test
      - name: Run tests
        run: npm run test

  deploy-testing:
    name: Deploy to test environment
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v6
      - name: Install Node 24
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
      - name: Build Next.js site
        run: npm run build
        env:
          DEVELOPMENT: true
      - name: Install Python 3
        uses: actions/setup-python@v6
        with:
          python-version: 3.12
      - name: Install AWS SAM
        uses: aws-actions/setup-sam@v2
      - name: Assume the testing pipeline user role
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ env.PIPELINE_USER_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.PIPELINE_USER_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.TESTING_REGION }}
          role-to-assume: ${{ env.TESTING_PIPELINE_EXECUTION_ROLE }}
          role-session-name: testing-deployment
          role-duration-seconds: 3600
          role-skip-session-tagging: true
      - name: Deploy test infrastructure
        run: |
          sam deploy --stack-name ${{ env.TESTING_STACK_NAME }} \
            --template-file ${{ env.TEMPLATE_NAME }} \
            --region ${{ env.TESTING_REGION }} \
            --no-fail-on-empty-changeset \
            --role-arn ${{ env.TESTING_CLOUDFORMATION_EXECUTION_ROLE }} \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides 'Environment=test'
      - name: Copy static site to test S3 bucket
        run: ./scripts/copyToS3.sh ${{ env.TESTING_S3_BUCKET }}

  deploy-production:
    name: Deploy to production
    if: github.ref == 'refs/heads/master'
    needs: [deploy-testing]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v6
      - name: Install Node 24
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
      - name: Build Next.js site
        run: npm run build
      - name: Install Python 3
        uses: actions/setup-python@v6
        with:
          python-version: 3.12
      - name: Install AWS SAM
        uses: aws-actions/setup-sam@v2
      - name: Assume the production pipeline user role
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ env.PIPELINE_USER_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.PIPELINE_USER_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.PROD_REGION }}
          role-to-assume: ${{ env.PROD_PIPELINE_EXECUTION_ROLE }}
          role-session-name: production-deployment
          role-duration-seconds: 3600
          role-skip-session-tagging: true
      - name: Deploy production infrastructure
        run: |
          sam deploy --stack-name ${{ env.PROD_STACK_NAME }} \
            --template-file ${{ env.TEMPLATE_NAME }} \
            --region ${{ env.PROD_REGION }} \
            --no-fail-on-empty-changeset \
            --role-arn ${{ env.PROD_CLOUDFORMATION_EXECUTION_ROLE }} \
            --capabilities CAPABILITY_NAMED_IAM
      - name: Copy static site to production S3 bucket
        run: ./scripts/copyToS3.sh ${{ env.PROD_S3_BUCKET }}

  bump:
    name: Bump the version number and tag the commit
    needs: [deploy-production]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v6
      - name: Install Node 24
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
      - name: Set git name and email
        run: |
          git config --local user.email "${{ env.GIT_EMAIL }}"
          git config --local user.name "github-actions[bot]"
      - name: Bump the minor version
        run: npm version minor
      - name: Push tag created by version bump
        run: git push --follow-tags
